### ISSUE TITLE
Message return output uses the wrong variable

### ISSUE THREAD

**Issue by tsit9** [MCD4290-Team5/Assignment1#9]
function decodeCameraImage(data)
{
	// ADD YOUR CODE HERE
	x = count(curate(data));
	signalConverting(x);
	messageField = word;
	return x;
}

Wouldn't returning x simply result in returning x = count(curate(data));?

**Comment by miraizu** [comment]
what does count() produce? isn't it producing true/false boolean? I thought it was the point of it.

**Comment by tsit9** [comment]
yeah, but the the output of x would be x = count(curate(data));, which would be true/false. A bootlean would be returned, instead of messageField.

**Comment by miraizu** [comment]
and if you check the skeleton code, the only thing that we can return to skeleton code is a boolean
